var keyMirror = require('keymirror');

var AntiFraudConstants = keyMirror({
    USER_INIT: null,
    USER_SEARCH: null,
    USER_LABEL: null,
    USER_DETAIL: null,
    USER_REMARK_UPDATE: null,
    DEVICE_SEARCH: null,
    DEVICE_LABEL: null,
    ORDER_SEARCH: null,
    FEATURE_INIT: null,
    FEATURE_REMOVE: null,
    FEATURE_SEARCH: null,
    FEATURE_ENTITY: null,
    ATTRIBUTE_INIT: null,
    ATTRIBUTE_ADD: null,
    ATTRIBUTE_DEL: null,
    ATTRIBUTE_ENTITY: null,
    LOGIN: null,
    LOGOUT: null,
    APP_INIT: null,
    APP_ENTITY: null,
    APP_DEL: null,
    APP_ADD: null,
    APP_UPDATE: null,
    STAT_INIT: null,
    TEAM_INIT: null,
    TEAM_ADD_MEMBER: null,
    TEAM_DEL_MEMBER: null,
    EVENT_SEARCH: null,
    NETWORK_USER: null,
    NETWORK_DEVICE: null,
    ENTITY_INIT: null,
    SCENE_CONVERT: null,
    SEARCH_IP_PROXY: null,
    SEARCH_FINANCE: null,
    BOOT_NOTIFICATION_DETECTION: null,
    SCAN_SYS_NOTIFICATIONS: null,
});

module.exports = AntiFraudConstants;
