var keyMirror = require('keymirror');

var MonitorConstants = keyMirror({
    ChangeToolBar: null,
    ChangeMenus: null,
    ChangeFirstMenus: null,
    SaveOperator: null,
    ChangeBreadcrumb: null,
    ChangeViews: null,
    GetVCenterList: null,
    GetVCenterTip: null,
    GetHypervisorList: null,
    GetGraphItemList: null,
    GetVmList: null,
    GetHistoryDataList: null,
    CreateVCenter: null,
    CreateDatabase: null,
    CreateGraphTemplate: null,
    CreateGraphItem: null,
    DeleteVCenter: null,
    DeleteDatabase: null,
    DeleteGraphItem: null,
    UpdateVCenter: null,
    UpdateGraphTemplate: null,
    DeleteGraphTemplate: null,
    GetGraphTemplateList: null,
    GetConfigData: null,
    SaveMonitorItemRefresh: null,
    AlarmLineSet: null,
    GetHypervisorTip: null,
    StartChartsRender: null,
    ChangeMysqlList: null,
    ChangeSqlserverList: null,
    ChangeApacheList: null,
    ChangeNginxList: null,
    CreateAppService: null,
    DeleteAppService: null,
    ChangeAlarmMessageList: null,
    ChangeHttpList: null
});

module.exports = MonitorConstants;
