/**
 * Created by Captain on 2016/6/22.
 */
monitorItems=
    {
        hypervisor:{
            "cpu使用情况":{
                items:[
                    /*"'vmware.hv.hw.cpu.threads[{$URL},{HOST.HOST}]'"*/
                    "'vmware.hv.cpu.usage[{$URL},{HOST.HOST}]'",
                    /*"'calc.vmware.hv.hw.cpu.all'"*/
                ],
                graphType:1,
                convertDataType:"memoryM",
                seriesType:[
                    "area",
                ],
                name:[
                    "cpu使用大小",
                    /*"cpu总大小"*/
                ]
            },
            "内存使用情况":{
                items:[
                    "'vmware.hv.memory.used[{$URL},{HOST.HOST}]'",
                    "'vmware.hv.hw.memory[{$URL},{HOST.HOST}]'"
                    /*"'vmware.hv.memory.size.ballooned[{$URL},{HOST.HOST}]'",*/
                ],
                seriesType:[
                    "area",
                    ""
                ],
                name:[
                    "内存使用大小",
                    "内存总大小"
                ],
                graphType:1,
                convertDataType:"memoryM"
            }

        },
        vms:{
            "cpu使用率":{
                items:[
                    {"vmware.vm.cpu.ready[{$URL},{HOST.HOST}]":""},
                    {"vmware.vm.cpu.usage[{$URL},{HOST.HOST}]":"cpu使用率"}
                ],
                graphType:"pieCharts"
            },
            "内存使用率":{
                items:[
                    {"vmware.vm.memory.size.ballooned[{$URL},{HOST.HOST}]":"膨胀内存"},
                    {"vmware.vm.memory.size.compressed[{$URL},{HOST.HOST}]":"压缩内存"},
                    {"vmware.vm.memory.size.private[{$URL},{HOST.HOST}]":"私有内存"},
                    {"vmware.vm.memory.size.shared[{$URL},{HOST.HOST}]":"共享内存"},
                    {"vmware.vm.memory.size.swapped[{$URL},{HOST.HOST}]":"交换内存"},
                    {"vmware.vm.memory.size.usage.guest[{$URL},{HOST.HOST}]":"guest使用量"},
                    {"vmware.vm.memory.size.usage.host[{$URL},{HOST.HOST}]":"host使用量"},
                    {"vmware.vm.memory.size[{$URL},{HOST.HOST}]":"内存总大小"}
                ],
                graphType:"lineCharts"
            }

        },
        mysql:{
            "mysql连接数":{
                items:[
                    "'mysql.status[Threads_running]'",
                    "'mysql.status[Threads_connected]'"
                ],
                graphType:1,
                convertDataType:"number",
                seriesType:[
                    "",
                    ""
                ],
                name:[
                    "mysql活跃连接数",
                    "mysql总连接数"
                ]
            },
            "mysql吞吐率":{
                items:[
                    "'mysql.status[Bytes_received]'",
                    "'mysql.status[Bytes_sent]'"
                ],
                graphType:1,
                convertDataType:"memoryK",
                seriesType:[
                    "",
                    ""
                ],
                name:[
                    "接收字节",
                    "发送字节"
                ]
            },

        },
        http:{
            "平均响应时间":{
                items:[
                    "'web.time[total,{$URL}]'"
                ],
                graphType:1,
                convertDataType:"second",
                seriesType:[
                    ""
                ],
                name:[
                    "平均响应时间"
                ]
            }

        },
        apache:{
            "请求统计":{
                items:[
                    "'apache[KeepAlive]'",
                    "'apache[ReadingRequest]'",
                    "'apache[SendingReply]'",
                    "'apache[WaitingForConnection]'",
                    "'apache[ClosingConnection]'",
                    "'apache[ReqPerSec]'"
                ],
                graphType:1,
                convertDataType:"number",
                seriesType:[
                    ""
                ],
                name:[
                    "持久连接",
                    "读取请求",
                    "发送相应内容",
                    "等待连接",
                    "关闭连接",
                    "并发数"
                ]
            },
            "吞吐率":{
                items:[
                    "'apache[BytesPerReq]'",
                    "'apache[BytesPerSec]'"
                ],
                graphType:1,
                convertDataType:"memoryK",
                seriesType:[
                    "",
                    ""
                ],
                name:[
                    "接收字节",
                    "发送字节"
                ]
            },

        },
        linux:{
            "Home使用量":{
                items:[
                    "'vfs.fs.size[/,total]'",
                    "'vfs.fs.size[/,used]'",
                ],
                graphType:1,
                convertDataType:"memoryM",
                seriesType:[
                    "",
                    "area"
                ],
                name:[
                    "Home总大小",
                    "Home已使用大小",
                ]
            },
            "Boot使用量":{
                items:[
                    "'vfs.fs.size[/boot,total]'",
                    "'vfs.fs.size[/boot,used]'",
                ],
                graphType:1,
                convertDataType:"memoryM",
                seriesType:[
                    "",
                    "area"
                ],
                name:[
                    "Boot总大小",
                    "Boot已使用大小",
                ]
            }
        }
    };
